import { MD3DarkTheme } from 'react-native-paper';
import type { MD3Theme } from 'react-native-paper';

export const colors = {
  bg:          '#0C0E16',
  surface:     '#141824',
  surfaceHigh: '#1C2236',
  surfaceTop:  '#232B42',
  primary:     '#C04A1A',
  primaryDim:  '#1E0B04',
  gold:        '#FFBE0B',
  goldDim:     '#2A2005',
  green:       '#22C55E',
  greenDim:    '#0D2A18',
  text1:       '#E8EAF2',
  text2:       '#8892A4',
  text3:       '#4E5670',
  border:      '#1F2540',
  error:       '#FF4D6D',
  errorDim:    '#2A0A10',
  debt:        '#E88C00',
} as const;

export const PeporraTheme: MD3Theme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary:              colors.primary,
    onPrimary:            '#ffffff',
    primaryContainer:     colors.primaryDim,
    onPrimaryContainer:   colors.primary,
    secondary:            colors.gold,
    onSecondary:          '#000000',
    secondaryContainer:   colors.primaryDim,
    onSecondaryContainer: colors.primary,
    tertiary:             colors.green,
    onTertiary:           '#000000',
    tertiaryContainer:    colors.greenDim,
    onTertiaryContainer:  colors.green,
    error:                colors.error,
    onError:              '#ffffff',
    errorContainer:       colors.errorDim,
    onErrorContainer:     colors.error,
    background:           colors.bg,
    onBackground:         colors.text1,
    surface:              colors.surface,
    onSurface:            colors.text1,
    surfaceVariant:       colors.surfaceHigh,
    onSurfaceVariant:     colors.text2,
    outline:              colors.border,
    outlineVariant:       colors.border,
    shadow:               '#000000',
    scrim:                '#000000',
    inverseSurface:       colors.text1,
    inverseOnSurface:     colors.bg,
    inversePrimary:       colors.primaryDim,
    elevation: {
      level0: 'transparent',
      level1: colors.surface,
      level2: colors.surfaceHigh,
      level3: colors.surfaceTop,
      level4: '#27304E',
      level5: '#2C3558',
    },
    surfaceDisabled:      `${colors.text1}1F`,
    onSurfaceDisabled:    `${colors.text1}61`,
    backdrop:             '#00000080',
  },
};
